#!/usr/bin/env bash

xrandr --output eDP1 --mode 2880x1800 --pos 2056x2880 --rotate normal --output DP1 --off --output DP2 --off --output HDMI1 --off --output HDMI2 --off --output HDMI3 --primary --mode 3440x1440 --scale 2x2 --pos 0x0 --rotate normal --output VIRTUAL1 --off
